
server:
  port: 8761
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    defaultZone: ${default.url}

#  server:
#    enable-self-preservation: false
#    eviction-interval-timer-in-ms: 5000

spring:
  profiles:
    active: dev

---

spring:
  profiles: dev
default:
  url: http://localhost:8761/eureka

---

spring:
  profiles: test
default:
  url: http://192.180.3.43:8761/eureka