server:
  port: 43201

spring:
  application:
    name: imp-sba
  boot:
    admin:
      context-path: /sba
management:
  security:
    enabled: false

eureka:
  client:
    service-url:
      defalutZone: ${default.url}
  instance:
    prefer-ip-address: true
#    instance-id: ${spring.application.name}(${spring.cloud.client.ipAddress}:${server.port})
#    status-page-url: http://${spring.cloud.client.ipAddress}:${server.port}/${server.content-path}
#    home-page-url-path: /${server.content-path}



info:
  app:
    name: "@project.name@"
    description: "@project.description@"
    version: "@project.version@"
    spring-boot-version: "@project.parent.version@"


---

spring:
  profiles: dev
default:
  url: http://localhost:8761/eureka/

---

spring:
  profiles: test
default:
  url: http://192.180.3.43:8761/eureka





